FROM python:alpine3.7 
RUN mkdir /python-order-service
COPY . /python-order-service
WORKDIR /python-order-service
RUN pip install -r requirements.txt 
EXPOSE 3000 
ENTRYPOINT [ "python" ] 
CMD [ "main.py" ]  